[package]
name = "nitf-rs"
version = "0.2.3"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Minimal NITF interface."
homepage = "https://github.com/holmesv3/nitf-rs"
readme = "README-crates.md"

[dependencies]
thiserror = "^1.0"
log = "0.4"
